### ISSUE TITLE
Darken ::selection pls?

### ISSUE THREAD

**Issue by knghtbrd** [RaitaroH/LinuxMint_Blog-Deepdark#1]
I found the selection background to be too bright.

I propose:

```css
::selection {
    background: #1b6600 !important;
    color: #fff !important;
}
```
